### ISSUE TITLE
Error when attempting to use Display MMIF annotations option

### ISSUE THREAD

**Issue by kjallen** [clamsproject/appliance#4]
A stack trace is received if I click the open link next to Display MMIF annotations in the history panel after processing a file.

To replicate with stock clams appliance:
* Use Get Data -> Text Selector to add a text file to process
* Under Text Tools, choose Spacy NLP and click execute on the data added in previous step
* After processing in History panel you will see 'Spacy Annotations', click to expand the job
* Click the 'open' link next to Display MMIF annotations, an additional tab is opened 
* A flask error and stacktrace are presented, with the following top level error:

requests.exceptions.ConnectionError
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /display_application/ebfb8f50c6abde6d/consumer-mmif-viz/open/e5939cde8e1f3714/data/galaxy.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9d0f189390>: Failed to establish a new connection: [Errno 111] Connection refused')

The url for the new tab uses the hostname rather than localhost, ie
http://my-macbook-pro.local:9001/display?file=http%3A%2F%2Flocalhost%3A8080%2Fdisplay_application%2Febfb8f50c6abde6d%2Fconsumer-mmif-viz%2Fopen%2Fe5939cde8e1f3714%2Fdata%2Fgalaxy.txt

**Comment by keighrim** [comment]
This issue is fixed via 1ecb58767180cbce880bbdf67df8e90ad2c7f65a. However, building a new CLAMS-appliance instance now will pull from newer versions of other components, which will break the MMIF display application.
